//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { ApiUrlProvider } from "./common";import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { DateTime, Duration } from "luxon";

export class Client extends ApiUrlProvider {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * Performs login
     * @return Token information after successful login
     */
    login(body: Body, signal?: AbortSignal): Promise<TokenResponse> {
        let url_ = this.baseUrl + "/api/v1/auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: AxiosResponse): Promise<TokenResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = TokenResponse.fromJS(resultData200);
            return Promise.resolve<TokenResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TokenResponse>(null as any);
    }

    /**
     * Performs logout
     * @return Successful logout
     */
    logout(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/logout";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLogout(_response);
        });
    }

    protected processLogout(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Refreshes a valid token
     * @return Token information after successful refresh
     */
    refreshToken(signal?: AbortSignal): Promise<TokenResponse> {
        let url_ = this.baseUrl + "/api/v1/auth/refresh";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRefreshToken(_response);
        });
    }

    protected processRefreshToken(response: AxiosResponse): Promise<TokenResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = TokenResponse.fromJS(resultData200);
            return Promise.resolve<TokenResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TokenResponse>(null as any);
    }

    /**
     * @return Job execution was queued successfully.
     */
    queueRefreshMedia(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/admin/media/refresh";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processQueueRefreshMedia(_response);
        });
    }

    protected processQueueRefreshMedia(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Queued jobs were retrieved successfully.
     */
    getQueuedJobs(signal?: AbortSignal): Promise<string[]> {
        let url_ = this.baseUrl + "/api/v1/admin/jobs/queue";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetQueuedJobs(_response);
        });
    }

    protected processGetQueuedJobs(response: AxiosResponse): Promise<string[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(item);
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<string[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<string[]>(null as any);
    }

    /**
     * @param page (optional) Page number
     * @param perPage (optional) Number of items per page
     * @return List of series
     */
    listSeries(page?: number | undefined, perPage?: number | undefined, signal?: AbortSignal): Promise<SeriesListPaginated> {
        let url_ = this.baseUrl + "/api/v1/series?";
        if (page === null)
            throw new Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (perPage === null)
            throw new Error("The parameter 'perPage' cannot be null.");
        else if (perPage !== undefined)
            url_ += "perPage=" + encodeURIComponent("" + perPage) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processListSeries(_response);
        });
    }

    protected processListSeries(response: AxiosResponse): Promise<SeriesListPaginated> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = SeriesListPaginated.fromJS(resultData200);
            return Promise.resolve<SeriesListPaginated>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<SeriesListPaginated>(null as any);
    }

    /**
     * @return List of series
     */
    recentlyUpdatedSeries(signal?: AbortSignal): Promise<SeriesListItem[]> {
        let url_ = this.baseUrl + "/api/v1/series/recentlyUpdated";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRecentlyUpdatedSeries(_response);
        });
    }

    protected processRecentlyUpdatedSeries(response: AxiosResponse): Promise<SeriesListItem[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SeriesListItem.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<SeriesListItem[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<SeriesListItem[]>(null as any);
    }

    /**
     * @param serieId Serie ID
     * @return Series information
     */
    getSerieById(serieId: number, signal?: AbortSignal): Promise<Series> {
        let url_ = this.baseUrl + "/api/v1/series/{serieId}";
        if (serieId === undefined || serieId === null)
            throw new Error("The parameter 'serieId' must be defined.");
        url_ = url_.replace("{serieId}", encodeURIComponent("" + serieId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetSerieById(_response);
        });
    }

    protected processGetSerieById(response: AxiosResponse): Promise<Series> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = Series.fromJS(resultData200);
            return Promise.resolve<Series>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<Series>(null as any);
    }

    /**
     * @param serieId Serie ID
     * @param page (optional) Page number
     * @param perPage (optional) Number of items per page
     * @return Chapter information
     */
    getChaptersForSeries(serieId: number, page?: number | undefined, perPage?: number | undefined, signal?: AbortSignal): Promise<ChapterListPaginated> {
        let url_ = this.baseUrl + "/api/v1/series/{serieId}/chapters?";
        if (serieId === undefined || serieId === null)
            throw new Error("The parameter 'serieId' must be defined.");
        url_ = url_.replace("{serieId}", encodeURIComponent("" + serieId));
        if (page === null)
            throw new Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (perPage === null)
            throw new Error("The parameter 'perPage' cannot be null.");
        else if (perPage !== undefined)
            url_ += "perPage=" + encodeURIComponent("" + perPage) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetChaptersForSeries(_response);
        });
    }

    protected processGetChaptersForSeries(response: AxiosResponse): Promise<ChapterListPaginated> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ChapterListPaginated.fromJS(resultData200);
            return Promise.resolve<ChapterListPaginated>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ChapterListPaginated>(null as any);
    }

    /**
     * @param serieId Serie ID
     * @param chapterId Chapter ID
     * @return List of pages
     */
    getPagesForChapter(serieId: number, chapterId: number, signal?: AbortSignal): Promise<string[]> {
        let url_ = this.baseUrl + "/api/v1/series/{serieId}/chapters/{chapterId}/pages";
        if (serieId === undefined || serieId === null)
            throw new Error("The parameter 'serieId' must be defined.");
        url_ = url_.replace("{serieId}", encodeURIComponent("" + serieId));
        if (chapterId === undefined || chapterId === null)
            throw new Error("The parameter 'chapterId' must be defined.");
        url_ = url_.replace("{chapterId}", encodeURIComponent("" + chapterId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetPagesForChapter(_response);
        });
    }

    protected processGetPagesForChapter(response: AxiosResponse): Promise<string[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(item);
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<string[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<string[]>(null as any);
    }

    /**
     * @param page (optional) Page number
     * @param perPage (optional) Number of items per page
     * @return List of staff members
     */
    listStaff(page?: number | undefined, perPage?: number | undefined, signal?: AbortSignal): Promise<StaffListPaginated> {
        let url_ = this.baseUrl + "/api/v1/staff?";
        if (page === null)
            throw new Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (perPage === null)
            throw new Error("The parameter 'perPage' cannot be null.");
        else if (perPage !== undefined)
            url_ += "perPage=" + encodeURIComponent("" + perPage) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processListStaff(_response);
        });
    }

    protected processListStaff(response: AxiosResponse): Promise<StaffListPaginated> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = StaffListPaginated.fromJS(resultData200);
            return Promise.resolve<StaffListPaginated>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<StaffListPaginated>(null as any);
    }

    /**
     * @param staffId Staff ID
     * @return Staff member information
     */
    getStaffById(staffId: number, signal?: AbortSignal): Promise<Staff> {
        let url_ = this.baseUrl + "/api/v1/staff/{staffId}";
        if (staffId === undefined || staffId === null)
            throw new Error("The parameter 'staffId' must be defined.");
        url_ = url_.replace("{staffId}", encodeURIComponent("" + staffId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetStaffById(_response);
        });
    }

    protected processGetStaffById(response: AxiosResponse): Promise<Staff> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = Staff.fromJS(resultData200);
            return Promise.resolve<Staff>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<Staff>(null as any);
    }
}

export class TokenResponse implements ITokenResponse {
    token!: string;
    token_type!: string;
    expires_in!: number;

    [key: string]: any;

    constructor(data?: ITokenResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.token = _data["token"] !== undefined ? _data["token"] : <any>null;
            this.token_type = _data["token_type"] !== undefined ? _data["token_type"] : <any>null;
            this.expires_in = _data["expires_in"] !== undefined ? _data["expires_in"] : <any>null;
        }
    }

    static fromJS(data: any): TokenResponse {
        data = typeof data === 'object' ? data : {};
        let result = new TokenResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["token"] = this.token !== undefined ? this.token : <any>null;
        data["token_type"] = this.token_type !== undefined ? this.token_type : <any>null;
        data["expires_in"] = this.expires_in !== undefined ? this.expires_in : <any>null;
        return data;
    }
}

export interface ITokenResponse {
    token: string;
    token_type: string;
    expires_in: number;

    [key: string]: any;
}

export class ErrorResponse implements IErrorResponse {
    /** Translation independent error message */
    message!: string;

    [key: string]: any;

    constructor(data?: IErrorResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.message = _data["message"] !== undefined ? _data["message"] : <any>null;
        }
    }

    static fromJS(data: any): ErrorResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ErrorResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["message"] = this.message !== undefined ? this.message : <any>null;
        return data;
    }
}

export interface IErrorResponse {
    /** Translation independent error message */
    message: string;

    [key: string]: any;
}

export class ChapterListPaginated implements IChapterListPaginated {
    data!: Chapter[];
    current_page!: number;
    records_per_page!: number;
    last_page!: number;
    total!: number;

    [key: string]: any;

    constructor(data?: IChapterListPaginated) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
            if (data.data) {
                this.data = [];
                for (let i = 0; i < data.data.length; i++) {
                    let item = data.data[i];
                    this.data[i] = item && !(<any>item).toJSON ? new Chapter(item) : <Chapter>item;
                }
            }
        }
        if (!data) {
            this.data = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(Chapter.fromJS(item));
            }
            else {
                this.data = <any>null;
            }
            this.current_page = _data["current_page"] !== undefined ? _data["current_page"] : <any>null;
            this.records_per_page = _data["records_per_page"] !== undefined ? _data["records_per_page"] : <any>null;
            this.last_page = _data["last_page"] !== undefined ? _data["last_page"] : <any>null;
            this.total = _data["total"] !== undefined ? _data["total"] : <any>null;
        }
    }

    static fromJS(data: any): ChapterListPaginated {
        data = typeof data === 'object' ? data : {};
        let result = new ChapterListPaginated();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item.toJSON());
        }
        data["current_page"] = this.current_page !== undefined ? this.current_page : <any>null;
        data["records_per_page"] = this.records_per_page !== undefined ? this.records_per_page : <any>null;
        data["last_page"] = this.last_page !== undefined ? this.last_page : <any>null;
        data["total"] = this.total !== undefined ? this.total : <any>null;
        return data;
    }
}

export interface IChapterListPaginated {
    data: IChapter[];
    current_page: number;
    records_per_page: number;
    last_page: number;
    total: number;

    [key: string]: any;
}

export class Chapter implements IChapter {
    id!: number;
    number!: number;
    pages_count!: number;

    [key: string]: any;

    constructor(data?: IChapter) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"] !== undefined ? _data["id"] : <any>null;
            this.number = _data["number"] !== undefined ? _data["number"] : <any>null;
            this.pages_count = _data["pages_count"] !== undefined ? _data["pages_count"] : <any>null;
        }
    }

    static fromJS(data: any): Chapter {
        data = typeof data === 'object' ? data : {};
        let result = new Chapter();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["number"] = this.number !== undefined ? this.number : <any>null;
        data["pages_count"] = this.pages_count !== undefined ? this.pages_count : <any>null;
        return data;
    }
}

export interface IChapter {
    id: number;
    number: number;
    pages_count: number;

    [key: string]: any;
}

export class Genre implements IGenre {
    id!: number;
    name!: string;

    [key: string]: any;

    constructor(data?: IGenre) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"] !== undefined ? _data["id"] : <any>null;
            this.name = _data["name"] !== undefined ? _data["name"] : <any>null;
        }
    }

    static fromJS(data: any): Genre {
        data = typeof data === 'object' ? data : {};
        let result = new Genre();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["name"] = this.name !== undefined ? this.name : <any>null;
        return data;
    }
}

export interface IGenre {
    id: number;
    name: string;

    [key: string]: any;
}

export class Series implements ISeries {
    id!: number;
    name!: string;
    chapter_count!: number;
    pages_count!: number;
    description!: string;
    synced!: boolean;
    image_url!: string | null;
    genres!: Genre[];
    staff!: StaffWithRole[];
    created_at!: DateTime;
    updated_at!: DateTime;

    [key: string]: any;

    constructor(data?: ISeries) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
            if (data.genres) {
                this.genres = [];
                for (let i = 0; i < data.genres.length; i++) {
                    let item = data.genres[i];
                    this.genres[i] = item && !(<any>item).toJSON ? new Genre(item) : <Genre>item;
                }
            }
            if (data.staff) {
                this.staff = [];
                for (let i = 0; i < data.staff.length; i++) {
                    let item = data.staff[i];
                    this.staff[i] = item && !(<any>item).toJSON ? new StaffWithRole(item) : <StaffWithRole>item;
                }
            }
        }
        if (!data) {
            this.genres = [];
            this.staff = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"] !== undefined ? _data["id"] : <any>null;
            this.name = _data["name"] !== undefined ? _data["name"] : <any>null;
            this.chapter_count = _data["chapter_count"] !== undefined ? _data["chapter_count"] : <any>null;
            this.pages_count = _data["pages_count"] !== undefined ? _data["pages_count"] : <any>null;
            this.description = _data["description"] !== undefined ? _data["description"] : <any>null;
            this.synced = _data["synced"] !== undefined ? _data["synced"] : <any>null;
            this.image_url = _data["image_url"] !== undefined ? _data["image_url"] : <any>null;
            if (Array.isArray(_data["genres"])) {
                this.genres = [] as any;
                for (let item of _data["genres"])
                    this.genres!.push(Genre.fromJS(item));
            }
            else {
                this.genres = <any>null;
            }
            if (Array.isArray(_data["staff"])) {
                this.staff = [] as any;
                for (let item of _data["staff"])
                    this.staff!.push(StaffWithRole.fromJS(item));
            }
            else {
                this.staff = <any>null;
            }
            this.created_at = _data["created_at"] ? DateTime.fromISO(_data["created_at"].toString()) : <any>null;
            this.updated_at = _data["updated_at"] ? DateTime.fromISO(_data["updated_at"].toString()) : <any>null;
        }
    }

    static fromJS(data: any): Series {
        data = typeof data === 'object' ? data : {};
        let result = new Series();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["name"] = this.name !== undefined ? this.name : <any>null;
        data["chapter_count"] = this.chapter_count !== undefined ? this.chapter_count : <any>null;
        data["pages_count"] = this.pages_count !== undefined ? this.pages_count : <any>null;
        data["description"] = this.description !== undefined ? this.description : <any>null;
        data["synced"] = this.synced !== undefined ? this.synced : <any>null;
        data["image_url"] = this.image_url !== undefined ? this.image_url : <any>null;
        if (Array.isArray(this.genres)) {
            data["genres"] = [];
            for (let item of this.genres)
                data["genres"].push(item.toJSON());
        }
        if (Array.isArray(this.staff)) {
            data["staff"] = [];
            for (let item of this.staff)
                data["staff"].push(item.toJSON());
        }
        data["created_at"] = this.created_at ? this.created_at.toString() : <any>null;
        data["updated_at"] = this.updated_at ? this.updated_at.toString() : <any>null;
        return data;
    }
}

export interface ISeries {
    id: number;
    name: string;
    chapter_count: number;
    pages_count: number;
    description: string;
    synced: boolean;
    image_url: string | null;
    genres: IGenre[];
    staff: IStaffWithRole[];
    created_at: DateTime;
    updated_at: DateTime;

    [key: string]: any;
}

export class SeriesListItem implements ISeriesListItem {
    id!: number;
    name!: string;
    chapter_count!: number;
    pages_count!: number;
    description!: string;
    synced!: boolean;
    image_url!: string | null;
    created_at!: DateTime;
    updated_at!: DateTime;

    [key: string]: any;

    constructor(data?: ISeriesListItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"] !== undefined ? _data["id"] : <any>null;
            this.name = _data["name"] !== undefined ? _data["name"] : <any>null;
            this.chapter_count = _data["chapter_count"] !== undefined ? _data["chapter_count"] : <any>null;
            this.pages_count = _data["pages_count"] !== undefined ? _data["pages_count"] : <any>null;
            this.description = _data["description"] !== undefined ? _data["description"] : <any>null;
            this.synced = _data["synced"] !== undefined ? _data["synced"] : <any>null;
            this.image_url = _data["image_url"] !== undefined ? _data["image_url"] : <any>null;
            this.created_at = _data["created_at"] ? DateTime.fromISO(_data["created_at"].toString()) : <any>null;
            this.updated_at = _data["updated_at"] ? DateTime.fromISO(_data["updated_at"].toString()) : <any>null;
        }
    }

    static fromJS(data: any): SeriesListItem {
        data = typeof data === 'object' ? data : {};
        let result = new SeriesListItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["name"] = this.name !== undefined ? this.name : <any>null;
        data["chapter_count"] = this.chapter_count !== undefined ? this.chapter_count : <any>null;
        data["pages_count"] = this.pages_count !== undefined ? this.pages_count : <any>null;
        data["description"] = this.description !== undefined ? this.description : <any>null;
        data["synced"] = this.synced !== undefined ? this.synced : <any>null;
        data["image_url"] = this.image_url !== undefined ? this.image_url : <any>null;
        data["created_at"] = this.created_at ? this.created_at.toString() : <any>null;
        data["updated_at"] = this.updated_at ? this.updated_at.toString() : <any>null;
        return data;
    }
}

export interface ISeriesListItem {
    id: number;
    name: string;
    chapter_count: number;
    pages_count: number;
    description: string;
    synced: boolean;
    image_url: string | null;
    created_at: DateTime;
    updated_at: DateTime;

    [key: string]: any;
}

export class SeriesListPaginated implements ISeriesListPaginated {
    data!: SeriesListItem[];
    current_page!: number;
    records_per_page!: number;
    last_page!: number;
    total!: number;

    [key: string]: any;

    constructor(data?: ISeriesListPaginated) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
            if (data.data) {
                this.data = [];
                for (let i = 0; i < data.data.length; i++) {
                    let item = data.data[i];
                    this.data[i] = item && !(<any>item).toJSON ? new SeriesListItem(item) : <SeriesListItem>item;
                }
            }
        }
        if (!data) {
            this.data = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(SeriesListItem.fromJS(item));
            }
            else {
                this.data = <any>null;
            }
            this.current_page = _data["current_page"] !== undefined ? _data["current_page"] : <any>null;
            this.records_per_page = _data["records_per_page"] !== undefined ? _data["records_per_page"] : <any>null;
            this.last_page = _data["last_page"] !== undefined ? _data["last_page"] : <any>null;
            this.total = _data["total"] !== undefined ? _data["total"] : <any>null;
        }
    }

    static fromJS(data: any): SeriesListPaginated {
        data = typeof data === 'object' ? data : {};
        let result = new SeriesListPaginated();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item.toJSON());
        }
        data["current_page"] = this.current_page !== undefined ? this.current_page : <any>null;
        data["records_per_page"] = this.records_per_page !== undefined ? this.records_per_page : <any>null;
        data["last_page"] = this.last_page !== undefined ? this.last_page : <any>null;
        data["total"] = this.total !== undefined ? this.total : <any>null;
        return data;
    }
}

export interface ISeriesListPaginated {
    data: ISeriesListItem[];
    current_page: number;
    records_per_page: number;
    last_page: number;
    total: number;

    [key: string]: any;
}

export class Staff implements IStaff {
    id!: number;
    name!: string;
    description!: string;
    image_url!: string;
    created_at!: DateTime;
    updated_at!: DateTime;

    [key: string]: any;

    constructor(data?: IStaff) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"] !== undefined ? _data["id"] : <any>null;
            this.name = _data["name"] !== undefined ? _data["name"] : <any>null;
            this.description = _data["description"] !== undefined ? _data["description"] : <any>null;
            this.image_url = _data["image_url"] !== undefined ? _data["image_url"] : <any>null;
            this.created_at = _data["created_at"] ? DateTime.fromISO(_data["created_at"].toString()) : <any>null;
            this.updated_at = _data["updated_at"] ? DateTime.fromISO(_data["updated_at"].toString()) : <any>null;
        }
    }

    static fromJS(data: any): Staff {
        data = typeof data === 'object' ? data : {};
        let result = new Staff();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["name"] = this.name !== undefined ? this.name : <any>null;
        data["description"] = this.description !== undefined ? this.description : <any>null;
        data["image_url"] = this.image_url !== undefined ? this.image_url : <any>null;
        data["created_at"] = this.created_at ? this.created_at.toString() : <any>null;
        data["updated_at"] = this.updated_at ? this.updated_at.toString() : <any>null;
        return data;
    }
}

export interface IStaff {
    id: number;
    name: string;
    description: string;
    image_url: string;
    created_at: DateTime;
    updated_at: DateTime;

    [key: string]: any;
}

export class StaffWithRole implements IStaffWithRole {
    id!: number;
    name!: string;
    description!: string;
    image_url!: string;
    created_at!: DateTime;
    updated_at!: DateTime;

    [key: string]: any;

    constructor(data?: IStaffWithRole) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"] !== undefined ? _data["id"] : <any>null;
            this.name = _data["name"] !== undefined ? _data["name"] : <any>null;
            this.description = _data["description"] !== undefined ? _data["description"] : <any>null;
            this.image_url = _data["image_url"] !== undefined ? _data["image_url"] : <any>null;
            this.created_at = _data["created_at"] ? DateTime.fromISO(_data["created_at"].toString()) : <any>null;
            this.updated_at = _data["updated_at"] ? DateTime.fromISO(_data["updated_at"].toString()) : <any>null;
        }
    }

    static fromJS(data: any): StaffWithRole {
        data = typeof data === 'object' ? data : {};
        let result = new StaffWithRole();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["name"] = this.name !== undefined ? this.name : <any>null;
        data["description"] = this.description !== undefined ? this.description : <any>null;
        data["image_url"] = this.image_url !== undefined ? this.image_url : <any>null;
        data["created_at"] = this.created_at ? this.created_at.toString() : <any>null;
        data["updated_at"] = this.updated_at ? this.updated_at.toString() : <any>null;
        return data;
    }
}

export interface IStaffWithRole {
    id: number;
    name: string;
    description: string;
    image_url: string;
    created_at: DateTime;
    updated_at: DateTime;

    [key: string]: any;
}

export class StaffListPaginated implements IStaffListPaginated {
    data!: StaffListPaginated[];
    current_page!: number;
    records_per_page!: number;
    last_page!: number;
    total!: number;

    [key: string]: any;

    constructor(data?: IStaffListPaginated) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
            if (data.data) {
                this.data = [];
                for (let i = 0; i < data.data.length; i++) {
                    let item = data.data[i];
                    this.data[i] = item && !(<any>item).toJSON ? new StaffListPaginated(item) : <StaffListPaginated>item;
                }
            }
        }
        if (!data) {
            this.data = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(StaffListPaginated.fromJS(item));
            }
            else {
                this.data = <any>null;
            }
            this.current_page = _data["current_page"] !== undefined ? _data["current_page"] : <any>null;
            this.records_per_page = _data["records_per_page"] !== undefined ? _data["records_per_page"] : <any>null;
            this.last_page = _data["last_page"] !== undefined ? _data["last_page"] : <any>null;
            this.total = _data["total"] !== undefined ? _data["total"] : <any>null;
        }
    }

    static fromJS(data: any): StaffListPaginated {
        data = typeof data === 'object' ? data : {};
        let result = new StaffListPaginated();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item.toJSON());
        }
        data["current_page"] = this.current_page !== undefined ? this.current_page : <any>null;
        data["records_per_page"] = this.records_per_page !== undefined ? this.records_per_page : <any>null;
        data["last_page"] = this.last_page !== undefined ? this.last_page : <any>null;
        data["total"] = this.total !== undefined ? this.total : <any>null;
        return data;
    }
}

export interface IStaffListPaginated {
    data: IStaffListPaginated[];
    current_page: number;
    records_per_page: number;
    last_page: number;
    total: number;

    [key: string]: any;
}

export class Body implements IBody {
    username!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: IBody) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.username = _data["username"] !== undefined ? _data["username"] : <any>null;
            this.password = _data["password"] !== undefined ? _data["password"] : <any>null;
        }
    }

    static fromJS(data: any): Body {
        data = typeof data === 'object' ? data : {};
        let result = new Body();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["username"] = this.username !== undefined ? this.username : <any>null;
        data["password"] = this.password !== undefined ? this.password : <any>null;
        return data;
    }
}

export interface IBody {
    username: string;
    password: string;

    [key: string]: any;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new SwaggerException(message, status, response, headers, result);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars